### ISSUE TITLE
起步报错

### ISSUE THREAD

**Issue by illionhh** [linjinze999/vue-llplatform#1]
嗨博主你好,我正在学习你的项目.不过我在起步阶段遇到了一些小问题,在引入Element后就出现一堆错误,希望得到你的帮助,感谢.以下为我的详细操作

# 起步

Last login: Fri Jan 18 10:40:43 on ttys000
your-hostname:~ joey$ vue init webpack vue-llplatform

? Project name vue-llplatform
? Project description A Vue.js project
? Author illion <18210723759@163.com>
? Vue build standalone
? Install vue-router? Yes
? Use ESLint to lint your code? Yes
? Pick an ESLint preset Standard
? Set up unit tests Yes
? Pick a test runner jest
? Setup e2e tests with Nightwatch? Yes
? Should we run `npm install` for you after the project has been created? (recom
mended) npm

   vue-cli · Generated "vue-llplatform".

# Installing project dependencies ...
# ========================

npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

> fsevents@1.2.6 install /Users/joey/vue-llplatform/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/joey/vue-llplatform/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> chromedriver@2.45.0 install /Users/joey/vue-llplatform/node_modules/chromedriver
> node install.js

Current existing ChromeDriver binary is unavailable, proceding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/2.45/chromedriver_mac64.zip
Saving to file: /var/folders/z9/m3t2s66n66d15c3f1rzy0kzw0000gn/T/chromedriver/chromedriver_mac64.zip

 
![](media/15477801471642/15477811446037.jpg)

![](media/15477801471642/15477813190453.jpg)

本地测试:

安装element:

![](media/15477801471642/15477815237756.jpg)

错误信息

![](media/15477801471642/15477826645770.jpg)

Last login: Fri Jan 18 11:14:15 on ttys000
your-hostname:~ joey$ npm i element-ui -s
+ element-ui@2.4.11
added 10 packages from 9 contributors and audited 11 packages in 8.698s
found 0 vulnerabilities

your-hostname:~ joey$ cd vue-llplatform
your-hostname:vue-llplatform joey$ npm run dev

> vue-llplatform@1.0.0 dev /Users/joey/vue-llplatform
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 94% asset optimization                                                       -         
 ERROR  Failed to compile with 1 errors                              11:34:43 AM

 error  in ../node_modules/element-ui/lib/theme-chalk/index.css

Module build failed: Error: No PostCSS Config found in: /Users/joey/node_modules/element-ui/lib/theme-chalk
    at config.load.then (/Users/joey/vue-llplatform/node_modules/postcss-load-config/src/index.js:55:15)

 @ ../node_modules/element-ui/lib/theme-chalk/index.css 4:14-186 13:3-17:5 14:22-194
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

 

 WAIT  Compiling...                                                  11:36:38 AM

 95% emitting                                                                 i    
 WARNING  Compiled with 1 warnings                                   11:36:39 AM

  ✘  http://eslint.org/docs/rules/spaced-comment  Expected space or tab after '//' in comment  
  src/main.js:6:35
  import ElementUI from 'element-ui'//第一行
                                     ^

  ✘  http://eslint.org/docs/rules/spaced-comment  Expected space or tab after '//' in comment  
  src/main.js:7:1
  //import 'element-ui/lib/theme-chalk/index.css'//第二行
   ^

  ✘  http://eslint.org/docs/rules/spaced-comment  Expected space or tab after '//' in comment  
  src/main.js:10:19
  Vue.use(ElementUI)//第三行
                     ^

✘ 3 problems (3 errors, 0 warnings)

Errors:
  3  http://eslint.org/docs/rules/spaced-comment

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 
下面这张图是再一次重头开始操作之后的报错信息..
![image](https://user-images.githubusercontent.com/34306229/51585450-5d803100-1f14-11e9-8e46-6db2358f93db.png)

**Comment by linjinze999** [comment]
1. 在根目录下创建`postcss.config.js`文件，写入以下内容试试，重新run试试：
```
module.exports = {
    plugins: {
        'autoprefixer': {browsers: 'last 5 version'}
    }
}
```
2. 后面看到你写了一些注释（第n行）不符合eslint规范，这也会导致项目无法运行，可以去掉注释或参考规范，在`//`后和文字间添加一个空格，注释单独占一行

**Comment by linjinze999** [comment]
另外我本地尝试重新安装了一遍，没有发现你这个问题，是否为版本不对或安装有误？
尝试安装一下阿里巴巴的npm镜像，重新装一遍依赖：
```
npm install -g cnpm --registry=https://registry.npm.taobao.org
cnpm install
cnpm i element-ui -S
```

**Comment by illionhh** [comment]
我把nodejs卸载重新安装了一遍,vue-llplatform运行没有问题,只是一引入这个element-ui就报错了,按照你的第一个提示我在根目录下创建了这个文件,run了一下还是报同样的错误..下面是我创建的目录截图,不知道是不是我理解错了

![image](https://user-images.githubusercontent.com/34306229/51598146-d0e76a00-1f37-11e9-8515-1a836cc21151.png)

我也试了下npm镜像,因为我有用美国的服务器,这个好像没什么影响哎...

我觉得就是这个element-ui的问题,我把它去掉就可以正常显示vue的本地界面了
(下面是我的操作截图)


 
 
 
![](media/15477801471642/15482348030440.jpg)

![](media/15477801471642/15482348141434.jpg)

安装淘宝镜像

![](media/15477801471642/15482354307210.jpg)

![](media/15477801471642/15482355200314.jpg)


**错误更新啦**
![](media/15477801471642/15482363137937.jpg)


![](media/15477801471642/15482372047930.jpg)


![](media/15477801471642/15482376944616.jpg)

**Comment by linjinze999** [comment]
`cnpm i element-ui -S`这个是大写`S`，另外根目录是指`vue-llplatform`下的目录，不是`src`源码目录
