### ISSUE TITLE
跨域请求

### ISSUE THREAD

**Issue by iwangshuai888** [linjinze999/vue-llplatform#3]
在跟SpringCloud对接的时候，后端已经处理所有的跨域请求信息了，前端也设置
![image](https://user-images.githubusercontent.com/31624863/56434854-fe5e6c80-6308-11e9-9897-cac2dd52bafb.png)
![image](https://user-images.githubusercontent.com/31624863/56434873-0f0ee280-6309-11e9-8e1d-a97355889461.png)
还是有
![image](https://user-images.githubusercontent.com/31624863/56434903-1fbf5880-6309-11e9-9560-c1c5424aad4c.png)

**Comment by linjinze999** [comment]
看起来你的后端响应头没有添加cors




| |
林锦泽
邮箱：linjinze999@163.com
|

签名由 网易邮箱大师 定制

在2019年04月20日 01:10，王煜鑫 写道：

在跟SpringCloud对接的时候，后端已经处理所有的跨域请求信息了，前端也设置


还是有
