### ISSUE TITLE
表格页面，点击头部的隐藏菜单，然后再点显示，主页面布局失控

### ISSUE THREAD

**Issue by torlinpeng** [linjinze999/vue-llplatform#4]
表格页面，点击头部的隐藏菜单，然后再点显示，主页面布局失控，出现横向滚动条，原因可能是因为table引起的

**Comment by linjinze999** [comment]
谢谢反馈，确实有这个问题，可能是布局设计不够合理导致的。

本项目作为教学示例，一些细节可能没有做好。等本人写完另外一个组件库后，可能会基于vue-cli3重写一下这个项目。

**Comment by torlinpeng** [comment]
加个微信一起研究呗，chenpeng2216 this is my Wechat
