### ISSUE TITLE
菜单栏，如果一级菜单下面无二级菜单，做不到该一级菜单隐藏

### ISSUE THREAD

**Issue by torlinpeng** [linjinze999/vue-llplatform#5]
<el-submenu :index="index1+''" v-if="level1.children.length > 1" :key="index1+''">
            <template slot="title"><i :class="level1.icon"></i><span slot="title">{{$t(level1.name)}}</span></template>
            <template v-for="(level2, index2) in level1.children">

**Comment by linjinze999** [comment]
这边比较恰当的做法是：获取所有菜单，过滤权限菜单，若某菜单无子菜单，则丢弃。将结果存储起来，在侧边栏中使用。

这个侧边栏现在有一些问题：
1. 用name来做侧边栏名称：Name在路由中是有意义的，可以新增一个title字段来作为名称；
2. 无法无限层级：该示例简单做了三个层级的判断，复杂且容易出错，并且父子菜单都存储在children中，通过length>1来判断是否有子目录，这个设计有点反人类，本问题应该就是这个设计写的不好导致的。有兴趣可以自己利用[函数式组件](https://cn.vuejs.org/v2/guide/render-function.html#%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BB%84%E4%BB%B6)来做无限子菜单
