### ISSUE TITLE
大佬 教程挂掉了

### ISSUE THREAD

**Issue by BIGduu** [linjinze999/vue-llplatform#6]
大佬教程挂掉了 能恢复下么 非常感谢

**Comment by linjinze999** [comment]
顶部导航或首页入口多点几下看看吧，我这边现在可以了。可能是Github Pages和项目的路径冲突导致的，最近准备基于Vue-CLI3重写一下项目，可能不是很稳定

**Comment by BIGduu** [comment]
好的非常感谢您的开源项目 这对我帮助非常的打
