### ISSUE TITLE
如何设置后端服务器地址

### ISSUE THREAD

**Issue by zhangyupeng233** [linjinze999/vue-llplatform#7]
我取消掉了mock, 然而请求总被发到http://localhost:8080/vue-llplatform/preview/api/users/login, 我现在有一个后台地址"http://121.23.21", 我该做什么才能让请求发到这个地址呢

**Comment by linjinze999** [comment]
直接拷贝我的代码吗？我的代码，如果是开发模式的话，修改这个文件：vue-llplatform/llplatform/.env.development；如果是线上部署，需要修改代理服务器（如Nginx）拦截api路径的请求到后台






| |
林锦泽
邮箱：linjinze999@163.com
|

签名由 网易邮箱大师 定制

在2019年08月15日 18:32，zhangyupeng233 写道：

我取消掉了mock, 然而请求总被发到http://localhost:8080/vue-llplatform/preview/api/users/login, 我现在有一个后台地址"http://121.23.21", 我该做什么才能让请求发到这个地址呢

**Comment by zhangyupeng233** [comment]
我在/.env.development中, 设置了VUE_APP_BACK_END_URL=https://16.23.24, 请求依然发到http://localhost:8080/vue-llplatform/preview/, 如果只有我自己有这个问题, 可以关闭这个issue了

**Comment by linjinze999** [comment]
这份代码因为要发布出来预览，所以我设置成固定使用mock了，还需要改这个文件（vue-llplatform/llplatform/src/main.js）里面搜一下mock，替换成被注释的那些代码




| |
林锦泽
邮箱：linjinze999@163.com
|

签名由 网易邮箱大师 定制

在2019年08月15日 18:53，zhangyupeng233 写道：

我在/.env.development中, 设置了VUE_APP_BACK_END_URL=https://16.23.24, 请求依然发到http://localhost:8080/vue-llplatform/preview/, 如果只有我自己有这个问题, 可以关闭这个issue了

**Comment by zhangyupeng233** [comment]
可以了, 感谢您的快速回复
