### ISSUE TITLE
nginx转发请求,后端收到的请求url中缺失api参数

### ISSUE THREAD

**Issue by zhangyupeng233** [linjinze999/vue-llplatform#8]
我想把请求发到http://172.16.15.208:8080/api/users/login
在llplatform\.env.development中 设置 VUE_APP_BACK_END_URL=http://172.16.15.208:8080
在src/api/user.js中 request('/api/users/login', params)
但是后端服务器接受到的url显示为 http://172.16.15.208:8080/users/login
url中的'api'不见了, 我怀疑和vue.config中的代理设置有关
我该如何设置才能让后端接收到正确的url呢

**Comment by linjinze999** [comment]
开发模式下：vue-llplatform/llplatform/vue.config.js  会将所有/api/请求重定向到你的url，但它只会截取api后面的url到你的url，你的url变量后面可加上/api/




| |
林锦泽
邮箱：linjinze999@163.com
|

签名由 网易邮箱大师 定制

在2019年08月16日 15:57，zhangyupeng233 写道：

我想把请求发到http://172.16.15.208:8080/api/users/login
在llplatform.env.development中 设置 VUE_APP_BACK_END_URL=http://172.16.15.208:8080
在src/api/user.js中 request('/api/users/login', params)
但是后端服务器接受到的url显示为 http://172.16.15.208:8080/users/login
url中的'api'不见了, 我怀疑和vue.config中的代理设置有关
我该如何设置才能让后端接收到正确的url呢

**Comment by zhangyupeng233** [comment]
是的  我把request('/api/users/login', params)  写成了request('/api/api/users/login', params),就可以访问了 还想问一下,  之后放到线上 需要单独的nginx服务器来做转发吗  我打包的时候依然按照request('/api/api/users/login', params),这样写吗
另外,应该在readme中放上二维码,请您喝杯咖啡

**Comment by linjinze999** [comment]
1. 这样设置就行，不用改请求：VUE_APP_BACK_END_URL=http://172.16.15.208:8080/api/
2. 加api前缀是为了方便nginx转发请求接口，区分静态文件，转发你可以看文档：https://linjinze999.github.io/vue-llplatform/docs/project/build.html
3. 我不建议直接使用这个项目代码，这份代码是教程代码而已。看文档理解整个项目，根据你的实际情况自己开发会更好：https://linjinze999.github.io/vue-llplatform




| |
林锦泽
邮箱：linjinze999@163.com
|

签名由 网易邮箱大师 定制

在2019年08月16日 16:12，zhangyupeng233 写道：

是的 我把request('/api/users/login', params) 写成了request('/api/api/users/login', params),就可以访问了 还想问一下, 之后放到线上 需要单独的nginx服务器来做转发吗 我打包的时候依然按照request('/api/api/users/login', params),这样写吗
另外,应该在readme中放上二维码,请您喝杯咖啡

**Comment by zhangyupeng233** [comment]
作为一个es6和vue的初学者,但是有一定js基础的人,  
感觉教程对我作用不大 只是讲了代码逻辑 和直接看代码没啥区别
我如果单纯按照vue官方教程 自己搭一个项目的话 有些费时费力   也会按照自己以前的习惯去写, 难以进步
我觉得我搞几天能把llplatform这个项目吃个差不多, 也学习下你的代码

**Comment by zhangyupeng233** [comment]
最终我还是按照官方文档自己弄的项目  把您的部分代码复制过去学习下
